### ISSUE TITLE
colin check fails with "load_config() got an unexpected keyword argument 'config_dict'"

### ISSUE THREAD

**Issue by dharmit** [user-cont/colin#134]
Based on https://github.com/user-cont/colin/issues/132#issuecomment-391351658, I installed `colin` with `pip2`. When I try to do `colin check` it fails with `load_config() got an unexpected keyword argument 'config_dict'`.

Sample output from run with `--debug`:
```bash
$ sudo colin check --debug -f /usr/share/colin/rulesets/fedora.json registry.fedoraproject.org/fedora:27
11:57:32.683 colin.py          DEBUG  Checking started.
11:57:32.683 target.py         DEBUG  Finding target 'registry.fedoraproject.org/fedora:27'.
11:57:32.683 backend.py        INFO   conu has initiated, welcome to the party!
11:57:32.683 backend.py        DEBUG  conu version: 0.3.1
11:57:32.698 __init__.py       INFO   docker environment info: 'Client:\n Version:         1.13.1\n API version:     1.26\n Package version: docker-1.13.1-51.git4032bd5.fc28.x86_64\n Go version:      go1.10\n Git commit:      c301b04-unsupported\n Built:           Wed Mar 28 13:53:29 2018\n OS/Arch:         linux/amd64\n\nServer:\n Version:         1.13.1\n API version:     1.26 (minimum version 1.12)\n Package version: docker-1.13.1-51.git4032bd5.fc28.x86_64\n Go version:      go1.10\n Git commit:      c301b04-unsupported\n Built:           Wed Mar 28 13:53:29 2018\n OS/Arch:         linux/amd64\n Experimental:    false\n'
11:57:32.699 colin.py          ERROR  An error occurred: TypeError("load_config() got an unexpected keyword argument 'config_dict'",)
Traceback (most recent call last):
  File "/bin/colin", line 11, in <module>
    load_entry_point('colin==0.0.4', 'console_scripts', 'colin')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/colin/cli/colin.py", line 79, in check
    tags=tag)
  File "/usr/lib/python2.7/site-packages/colin/core/colin.py", line 45, in run
    logging_level=logging_level)
  File "/usr/lib/python2.7/site-packages/colin/core/target.py", line 54, in __init__
    self.instance = Target._get_target_instance(target, logging_level=logging_level)
  File "/usr/lib/python2.7/site-packages/colin/core/target.py", line 80, in _get_target_instance
    with DockerBackend(logging_level=logging_level) as backend:
  File "/usr/lib/python2.7/site-packages/conu/backend/docker/backend.py", line 75, in __init__
    self.d = get_client()
  File "/usr/lib/python2.7/site-packages/conu/backend/docker/client.py", line 37, in get_client
    client = docker.APIClient(version="auto")  # >= 2
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 110, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'
```

Similar results when trying to run a check against a running container:
```bash
$ docker ps
CONTAINER ID        IMAGE                                  COMMAND             CREATED             STATUS              PORTS               NAMES
c224fd48add9        registry.fedoraproject.org/fedora:27   "sleep 300"         4 minutes ago       Up 4 minutes                            some-fedora

$ sudo colin check --debug -f /usr/share/colin/rulesets/default.json some-fedora
11:58:57.780 colin.py          DEBUG  Checking started.
11:58:57.780 target.py         DEBUG  Finding target 'some-fedora'.
11:58:57.780 backend.py        INFO   conu has initiated, welcome to the party!
11:58:57.780 backend.py        DEBUG  conu version: 0.3.1
11:58:57.794 __init__.py       INFO   docker environment info: 'Client:\n Version:         1.13.1\n API version:     1.26\n Package version: docker-1.13.1-51.git4032bd5.fc28.x86_64\n Go version:      go1.10\n Git commit:      c301b04-unsupported\n Built:           Wed Mar 28 13:53:29 2018\n OS/Arch:         linux/amd64\n\nServer:\n Version:         1.13.1\n API version:     1.26 (minimum version 1.12)\n Package version: docker-1.13.1-51.git4032bd5.fc28.x86_64\n Go version:      go1.10\n Git commit:      c301b04-unsupported\n Built:           Wed Mar 28 13:53:29 2018\n OS/Arch:         linux/amd64\n Experimental:    false\n'
11:58:57.795 colin.py          ERROR  An error occurred: TypeError("load_config() got an unexpected keyword argument 'config_dict'",)
Traceback (most recent call last):
  File "/bin/colin", line 11, in <module>
    load_entry_point('colin==0.0.4', 'console_scripts', 'colin')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/colin/cli/colin.py", line 79, in check
    tags=tag)
  File "/usr/lib/python2.7/site-packages/colin/core/colin.py", line 45, in run
    logging_level=logging_level)
  File "/usr/lib/python2.7/site-packages/colin/core/target.py", line 54, in __init__
    self.instance = Target._get_target_instance(target, logging_level=logging_level)
  File "/usr/lib/python2.7/site-packages/colin/core/target.py", line 80, in _get_target_instance
    with DockerBackend(logging_level=logging_level) as backend:
  File "/usr/lib/python2.7/site-packages/conu/backend/docker/backend.py", line 75, in __init__
    self.d = get_client()
  File "/usr/lib/python2.7/site-packages/conu/backend/docker/client.py", line 37, in get_client
    client = docker.APIClient(version="auto")  # >= 2
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 110, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'
```

Am I doing something wrong here? 

Version info:
```bash
$ sudo colin -V
colin, version 0.0.4

$ rpm -q python2-conu
rpm -q python2-conu

$ rpm -q python2-dockerfile-parse
python2-dockerfile-parse-0.0.10-1.fc28.noarch

$ rpm -qa | grep docker
python2-dockerfile-parse-0.0.10-1.fc28.noarch
docker-1.13.1-51.git4032bd5.fc28.x86_64
python3-docker-3.2.1-1.fc28.noarch
docker-common-1.13.1-51.git4032bd5.fc28.x86_64
python2-docker-3.2.1-1.fc28.noarch
docker-rhel-push-plugin-1.13.1-51.git4032bd5.fc28.x86_64
python3-docker-pycreds-0.2.2-2.fc28.noarch
python2-docker-pycreds-0.2.2-2.fc28.noarch
```

**Comment by TomasTomecek** [comment]
Looks like you've hit this issue: https://github.com/docker/docker-py/issues/1916

I can see that your python2-docker package is new-enough: `python2-docker-3.2.1-1.fc28.noarch`.

Therefore I'm not sure what the problem is exactly.

**Comment by TomasTomecek** [comment]
We have updated colin and conu in F28, is this issue still relevant?
