### ISSUE TITLE
colin does not work from GitHub installation

### ISSUE THREAD

**Issue by phracek** [user-cont/colin#17]
I tried to install and use `colin` locally but it fails.

~~~
$ colin -h
Traceback (most recent call last):
  File "/usr/bin/colin", line 11, in <module>
    load_entry_point('colin==0.0.1', 'console_scripts', 'colin')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/colin-0.0.1-py2.7.egg/colin/__init__.py", line 1, in <module>
    from .core.colin import run
  File "/usr/lib/python2.7/site-packages/colin-0.0.1-py2.7.egg/colin/core/colin.py", line 1, in <module>
    from colin.core.check_runner import go_through_checks
ImportError: No module named core.check_runner
~~~

**Comment by phracek** [comment]
I have installed `colin` by command `sudo python setup.py install`. Installation works, but `colin` itself does not work.

**Comment by lachmanfrantisek** [comment]
Not sure, if this can be problem, but:

- colin does not work for python2.7 now (due to dynamic loading)
- colin needs fresh conu (due to target type resolution)

**Comment by lachmanfrantisek** [comment]
Probably some problem in `setup.py`. This works well:

`docker run -it fedora:27 bash`:
```
dnf install git python3-devel python3-pyxattr
git clone https://github.com/user-cont/colin
cd colin/
pip3 install .
colin -h
```

**Comment by lachmanfrantisek** [comment]
Another problem will be with the config files. How can I copy them in `setup.py`?

**Comment by TomasTomecek** [comment]
http://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files

**Comment by lachmanfrantisek** [comment]
@TomasTomecek  thanks.

@phracek The problem above is with python2 and imports. I will correct it.

**Comment by phracek** [comment]
Issue is solved. Tested on Standard-testing-roles.
